<?php

namespace App\Enums;

enum ModificationPOs: string
{
    case ACQ = "ACQ";
    case CONSULTANCY = "CONSULTANCY";
    case MOD = "MOD";
    case GF_TOWERS = "GF_TOWERS";
    case ROLLOUT = "ROLLOUT";
    case GENERATOR = "GENERATOR";
    case L1_CONTRACT = "L1_CONTRACT";
    case CABINETS_RECTIFIERS = "CABINETS_&_RECTIFIERS";
    case BATTERIES = "BATTERIES";
    case CAMOUFLAGE_SOLUTIONS = "CAMOUFLAGE_SOLUTIONS";
    case GUARDING_HUTS = "GUARDING_HUTS";
    case TOWERS_MASTS = "TOWERS_&_MASTS";
    case PRECAST_FOUNDATION = "PRECAST_FOUNDATION";
    case FEEDERS_AND_ACCESSORIES = "FEEDERS_AND_ACCESSORIES";
    case CABLING = "CABLING";
    case RETROFITTING = "RETROFITTING";
    case E_BAND_PROJECT_MODIFICATION = "E-BAND_PROJECT_MODIFICATION";
    case MOD_G2G = "MOD_G2G";
    case POWER_MOD = "POWER_MOD";
    case CIVIL_CONS = "CIVIL_CONS";
    case CABLES = "CABLES";
    case ATS_PANEL = "ATS_PANEL";
    case SHELTERS = "SHELTERS";
    case FULL_NIGHT_TIME_BEACON_SYSTEM = "FULL_NIGHT_TIME_BEACON_SYSTEM";
    case MSC_MOD = "MSC_MOD";
    case SPLITTERS = "SPLITTERS";
    case RENTED_GENERATOR = "RENTED_GENERATOR";
    case RAISED_FLOOR = "RAISED_FLOOR";
    case POWER_OPERATIONAL_NEEDS = "POWER_OPERATIONAL_NEEDS";
    case STABILIZER = "STABILIZER";
    case HC_FOR_SPARE_MANAGEMENT = "HC_FOR_SPARE_MANAGEMENT";
    case B2B = "B2B";
    case POWER_METERS = "POWER_METERS";
    case TUNNEL_DRILLING = "TUNNEL_DRILLING";
    case MOD_MSC = "MOD_MSC";
    case STEEL_CAGES = "STEEL_CAGES";
    case PANEL_STANDS = "PANEL_STANDS";
    case SUPER_SILENT_GENERATORS = "SUPER_SILENT_GENERATORS";
    case ACS = "A/CS";
    case FIREMATIC_UNITS = "FIREMATIC_UNITS";
    case ROLLOUT_HK = "ROLLOUT-HK";
    case QS_MS_MOD = "QS_&_MS_MOD";
}
